# Generated by Django 5.1.1 on 2024-10-09 11:27

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avaliarImc',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('1', 'Feminino'), ('2', 'Masculino'), ('3', 'Não Binário'), ('4', 'outro'), ('5', 'Prefiro não dizer')], max_length=3, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso em kg')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura em metros')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='avaliados', variations={'thumb': (125, 125)}, verbose_name='foto da pessoa avaliada')),
            ],
        ),
    ]
